countries = ['Canada', 'Philippines', 'Australia', 'United Kingdom', 'France', 'Greece']
print("Here is the original Country list:")
print(countries)
print("\nHere is the sorted Country list:")
countries.sort()
print(countries)
print("\nHere is the Country list in reverse-alphabetical order:")
countries.sort(reverse=True)
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
print("\nHere's the list in alphabetical order.")
countries.sort()
print(countries)
print("\nHere's the list in reverse-alphabetical order.")
countries.sort(reverse=True)
print(countries)
print(len(countries))
