locations = ['Manila', 'Helsinki', 'London', 'Paris', 'Rome']
print("Here is the original location list:")
print(locations)
print("\n Here is the sorted list:")
locations.sort()
print(locations)
print("\n Here is the list in reverse-alphabetical order:")
locations.sort(reverse=True)
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
print("\n Here's the list in alphabetical order.")
locations.sort()
print(locations)
print("\n Here's the list in reverse-alphabetical order.")
locations.sort(reverse=True)
print(locations)
